language: python

python:
  - 3.6

dist: trusty

os:
  - linux
#  - osx

# remember OS X still doesn't have Python at all on Travis!

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc ncurses;
      fi

install: 
    - export FC=gfortran
    - cd bin
    - cmake ..
    - make
    - cd ..

script:
    - python tests/test.py

